services:
  - type: web
    name: nahalprat-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: FLASK_APP=app:create_app flask db upgrade && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: nahalprat-db
          property: connectionString
      - key: FLASK_APP
        value: app:create_app
    # All other environment variables should be set in Render Dashboard
    # See .env_production_backend for required variables


databases:
  - name: nahalprat-db

