"""fix available_spots column

Revision ID: a1b2c3d4e5f6
Revises: f1a2b3c4d5e6
Create Date: 2025-10-05 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new available_spots column
    op.add_column('trek_date', sa.Column('available_spots', sa.Integer(), nullable=True))
    
    # Migrate data: Use available_spots_basic as the default value for available_spots
    # This assumes basic is the most common package type
    op.execute('UPDATE trek_date SET available_spots = COALESCE(available_spots_basic, 20) WHERE available_spots IS NULL')
    
    # Drop the old package-specific columns
    op.drop_column('trek_date', 'available_spots_premium')
    op.drop_column('trek_date', 'available_spots_pro')
    op.drop_column('trek_date', 'available_spots_basic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Re-add the old columns
    op.add_column('trek_date', sa.Column('available_spots_basic', sa.INTEGER(), nullable=True))
    op.add_column('trek_date', sa.Column('available_spots_pro', sa.INTEGER(), nullable=True))
    op.add_column('trek_date', sa.Column('available_spots_premium', sa.INTEGER(), nullable=True))
    
    # Migrate data back: Copy available_spots to available_spots_basic
    op.execute('UPDATE trek_date SET available_spots_basic = available_spots')
    
    # Drop the new column
    op.drop_column('trek_date', 'available_spots')
    # ### end Alembic commands ###